-- 둘째마당 5장

-- WHERE절은 filter in R 역할 
SELECT *
    FROM EMP
  WHERE DEPTNO = 30;

-- 논리연산자 AND OR과 함께 사용
SELECT *
    FROM EMP
  WHERE DEPTNO = 30
    AND JOB = 'SALESMAN';
    
SELECT *
    FROM EMP
  WHERE DEPTNO = 30
    OR JOB = 'CLERK';
    
-- 산술연산자
SELECT *
    FROM EMP
  WHERE SAL * 12 = 36000;

-- 비교연산자
SELECT *
    FROM EMP
  WHERE SAL >= 3000;

-- 문자도 비교 가능
SELECT *
    FROM EMP
  WHERE ENAME >= 'F'; 
    
SELECT *
    FROM EMP
  WHERE ENAME <= 'FORZ'; 

-- != is same as <> and ^=
SELECT *
    FROM EMP
  WHERE SAL != 3000; 

SELECT *
    FROM EMP
  WHERE NOT SAL = 3000; 

-- IN 연산자 
SELECT *
    FROM EMP
  WHERE JOB = 'MANAGER'
     OR JOB = 'SALESMAN'
     OR JOB = 'CLERK';

SELECT *
    FROM EMP
  WHERE JOB IN ('MANAGER', 'SALESMAN', 'CLERK');
 
SELECT *
    FROM EMP
  WHERE JOB != 'MANAGER'
     AND JOB <> 'SALESMAN'
     AND JOB ^= 'CLERK';

SELECT *
    FROM EMP
  WHERE JOB NOT IN ('MANAGER', 'SALESMAN', 'CLERK');

-- BETWEEN A AND B
SELECT *
    FROM EMP
  WHERE SAL >= 2000
    AND SAL <= 3000;

SELECT *
    FROM EMP
  WHERE SAL BETWEEN 2000 AND 3000;
 
SELECT *
    FROM EMP
  WHERE SAL NOT BETWEEN 2000 AND 3000;

-- LIKE 연산자는 일부 문자열이 포함된 데이터를 조회할 때 사용
-- _와 %는 와일드카드
-- _는 any a character data, %는 모든 문자 데이터, \로 이스케이프
SELECT *
    FROM EMP
  WHERE ENAME LIKE 'S%';
  
SELECT *
    FROM EMP
  WHERE ENAME LIKE '_L%';

SELECT *
    FROM EMP
  WHERE ENAME LIKE '%AM%';
  
SELECT *
    FROM EMP
  WHERE ENAME NOT LIKE '%AM%';

-- IS NULL 연산자
SELECT ENAME, SAL, SAL*12*COMM AS ANNSAL, COMM
    FROM EMP;
    
SELECT *
    FROM EMP
  WHERE COMM = NULL; -- 비교 연산으로는 NULL값이 나오지 않음
  
SELECT *
    FROM EMP
  WHERE COMM IS NULL; -- 그래서 IS NULL 사용
  
SELECT *
    FROM EMP
  WHERE COMM IS NOT NULL;
  
SELECT *
    FROM EMP
  WHERE SAL > NULL
    AND COMM IS NULL; -- 출력물 X
    
SELECT *
    FROM EMP
  WHERE SAL > NULL
     OR COMM IS NULL; -- 출력물 O
     
-- 집합 연산자
-- 각 SELECT문이 출력하려는 열 개수와 각 열의 자료형이 순서별로 일치해야함
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO = 20;
  
-- 예컨대 아래 SQL문들은 에러 발생
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL
    FROM EMP
  WHERE DEPTNO = 20;
  
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO = 10
UNION
SELECT ENAME, EMPNO, DEPTNO, SAL
    FROM EMP
  WHERE DEPTNO = 20;

-- 따라서 오히려 아래처럼 열 이름이 다른 것은 개의치 않음
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO = 10
UNION
SELECT SAL, JOB, DEPTNO, SAL
    FROM EMP
  WHERE DEPTNO = 20;
  
-- UNION: 합집합. 중복 제거
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO = 10;

-- UNION ALL: 합집합. 중복 유지
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO = 10
UNION ALL
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO = 10;
  
-- MINUS: 차집합
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
MINUS
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO = 10;
  
-- INTERSECT: 교집합
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
INTERSECT
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO = 10;

-- P.125 QUIZ 1
SELECT *
    FROM EMP
  WHERE ENAME LIKE '%S';
  
-- P.125 QUIZ 2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO = 30
    AND JOB = 'SALESMAN';
    
-- P.125 QUIZ 3
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO BETWEEN 20 AND 30
    AND SAL > 2000;
    
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO BETWEEN 20 AND 30
INTERSECT
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
    FROM EMP
  WHERE SAL > 2000;
  
-- P.125 QUIZ 4
SELECT *
    FROM EMP
  WHERE SAL < 2000
     OR SAL > 3000;
     
-- P.125 QUIZ 5
SELECT ENAME, EMPNO, SAL, DEPTNO
    FROM EMP
  WHERE ENAME LIKE '%E%'
    AND DEPTNO = 30
    AND SAL NOT BETWEEN 1000 AND 2000;
    
-- P.125 QUIZ 6
SELECT *
    FROM EMP
  WHERE COMM IS NULL
    AND JOB IN ('MANAGER', 'CLERK')
    AND ENAME NOT LIKE '_L%';