-- P.92 QUIZ 2
SELECT DISTINCT JOB FROM EMP;

-- P.92 QUIZ 3
SELECT ALL EMPNO AS EMPLOYEE_NO, ENAME AS EMPLOYEE_NAME,
           MGR AS MANAGER, SAL AS SALARY, COMM AS COMMISSION,
           DEPTNO AS DEPARTMENT_NO
    FROM EMP
  ORDER BY DEPTNO DESC, EMPNO ASC;
