-- P.125 QUIZ 1
SELECT *
    FROM EMP
  WHERE ENAME LIKE '%S';
  
-- P.125 QUIZ 2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO = 30
    AND JOB = 'SALESMAN';
    
-- P.125 QUIZ 3
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO BETWEEN 20 AND 30
    AND SAL > 2000;
    
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO BETWEEN 20 AND 30
INTERSECT
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
    FROM EMP
  WHERE SAL > 2000;
  
-- P.125 QUIZ 4
SELECT *
    FROM EMP
  WHERE SAL < 2000
     OR SAL > 3000;
     
-- P.125 QUIZ 5
SELECT ENAME, EMPNO, SAL, DEPTNO
    FROM EMP
  WHERE ENAME LIKE '%E%'
    AND DEPTNO = 30
    AND SAL NOT BETWEEN 1000 AND 2000;
    
-- P.125 QUIZ 6
SELECT *
    FROM EMP
  WHERE COMM IS NULL
    AND JOB IN ('MANAGER', 'CLERK')
    AND ENAME NOT LIKE '_L%';
